TlsError: Rename the EOF enum value.
	* gio/src/error.hg (EOF): Rename it to ENDOFFILE to avoid a clash with
	another definition of the identifier somewhere else which breaks the
	gtkmm build.