meson: Use /utf-8 for Visual Studio builds
This way, we can avoid warning/error C4819 when building glibmm due to unicode
handling issues in the compiler, which is likely to pop up on East Asian
locales on Windows.

We need to ignore warning C4828 when building gendef.exe though with this.