RemoteActionGroup: Rename some vfuncs to add _full().
Rename activate_action_vfunc() to activate_action_full_vfunc() ad
rename change_action_state_vfunc() to change_action_state_full_vfunc(),
matching the underlying C vfuncs.
Now that this class derives from ActionGroup, this was causing warnings
such as this, at least with clang++:

/opt/gnome/include/giomm-2.52/giomm/remoteactiongroup.h:180:18: error: 'Gio::RemoteActionGroup::activate_action_vfunc' hides overloaded virtual
      function [-Werror,-Woverloaded-virtual]
    virtual void activate_action_vfunc(const Glib::ustring& action_name, const Glib::VariantBase& parameter, const Glib::VariantBase& platform_data);
                 ^
/opt/gnome/include/giomm-2.52/giomm/actiongroup.h:574:18: note: hidden overloaded virtual function 'Gio::ActionGroup::activate_action_vfunc' declared
      here: different number of parameters (2 vs 3)
    virtual void activate_action_vfunc(const Glib::ustring& name, const Glib::VariantBase& parameter);