Build: Tiny wihtespace fix to really generate posix-only files.
This typo was introduced in this recent commit:
https://git.gnome.org/browse/glibmm/commit/?id=05f9faf2476904f6b9210ca9935d4a081cc13421
and caused, for intance, unixdflist.h to not be generated, leading to
this build error:

../giomm/dbusmessage.h:31:31: fatal error: giomm/unixfdlist.h: No such
file or directory