Examples: Avoid a warning about unused code.
This useful warning seems to be new in g++ 6:

thread/dispatcher2.cc:88:1: error: ‘{anonymous}::ThreadTimer::~ThreadTimer()’ defined but not used [-Werror=unused-function]
 ThreadTimer::~ThreadTimer()